###
GET http://localhost:3000

###
GET http://localhost:3000/api/v1
###
GET http://localhost:3000/api/v1/products
###
GET http://localhost:3000/api/v1/products/64f955b6e0866f8ea99defc9
###
POST http://localhost:3000/api/v1/products
Content-Type: application/json

{
  "name": "Produto 05",
  "price": "700",
  "stock": "150"
}


###
PUT http://localhost:3000/api/v1/products/64f954fddbe69c1312bf92f2
Content-Type: application/json

{
  "name": "Produto 02",
  "price": "850",
  "stock": "20"
}

###
DELETE http://localhost:3000/api/v1/products/64f9539efc577d8c4e163c63
